/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelanimal.interfaztarea.vista;

import java.awt.Color;
import javax.swing.JSpinner;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Leo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        NuevaMascota = new javax.swing.JPanel();
        InscribirBttn = new javax.swing.JButton();
        DatosMascota = new javax.swing.JPanel();
        NombreMascota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ComboEspecie = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        SpinnerDias2 = new javax.swing.JSpinner();
        jLabel94 = new javax.swing.JLabel();
        DatosOwner = new javax.swing.JPanel();
        NombreOwner = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NumeroTelefono = new javax.swing.JTextField();
        DatosContrato = new javax.swing.JPanel();
        FechaIngreso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SpinnerDias = new javax.swing.JSpinner();
        PrecioFinal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PrecioPDia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ResetBttn = new javax.swing.JButton();
        Alimentar = new javax.swing.JPanel();
        DatosMascota1 = new javax.swing.JPanel();
        TiempoComidaPerro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TiempoComidaGato = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TiempoComidaPez = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TiempoComidaAve = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        DatosMascota2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ComidaDisponiblePerro = new javax.swing.JTextField();
        ComidaDisponibleGato = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ComidaDisponiblePez = new javax.swing.JTextField();
        ComidaDisponibleAve = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        AlimentarCompletoBttn = new javax.swing.JButton();
        ConflictoBttn = new javax.swing.JButton();
        Comida = new javax.swing.JPanel();
        DatosMascota3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ComboEspecieComida = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        SpinnerDias1 = new javax.swing.JSpinner();
        DatosMascota21 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        ComidaDisponiblePerro18 = new javax.swing.JTextField();
        ComidaDisponibleGato18 = new javax.swing.JTextField();
        jLabel89 = new javax.swing.JLabel();
        ComidaDisponiblePez18 = new javax.swing.JTextField();
        ComidaDisponibleAve18 = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        InscribirBttn1 = new javax.swing.JButton();
        GestionEspecie = new javax.swing.JPanel();
        DatosMascota5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        ComboEspecieComida2 = new javax.swing.JComboBox<>();
        InscribirBttn3 = new javax.swing.JButton();
        DatosMascota25 = new javax.swing.JPanel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        ComidaDisponiblePerro20 = new javax.swing.JTextField();
        ComidaDisponibleGato20 = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        ComidaDisponiblePez20 = new javax.swing.JTextField();
        ComidaDisponibleAve20 = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        Conflicto = new javax.swing.JPanel();
        DatosMascota22 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        ComboCausa = new javax.swing.JComboBox<>();
        ComboMascotaInforme = new javax.swing.JComboBox<>();
        SpinnerFecha = new javax.swing.JSpinner();
        jLabel99 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetalleTxt = new javax.swing.JTextPane();
        GuardarBttn = new javax.swing.JButton();
        LimpiarBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Animal 0mg");
        setName("VentanaPrincipal"); // NOI18N

        PanelPrincipal.setBackground(new java.awt.Color(107, 140, 58));

        jTabbedPane1.setBackground(new java.awt.Color(74, 89, 42));
        jTabbedPane1.setForeground(new java.awt.Color(217, 185, 126));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        NuevaMascota.setBackground(new java.awt.Color(220, 232, 242));

        InscribirBttn.setBackground(new java.awt.Color(217, 185, 126));
        InscribirBttn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        InscribirBttn.setForeground(new java.awt.Color(74, 89, 42));
        InscribirBttn.setText("Inscribir mascota");
        InscribirBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribirBttnActionPerformed(evt);
            }
        });

        DatosMascota.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de la mascota", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosMascota.setOpaque(false);

        NombreMascota.setBackground(new java.awt.Color(166, 81, 73));
        NombreMascota.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        NombreMascota.setForeground(new java.awt.Color(217, 185, 126));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(74, 89, 42));
        jLabel2.setText("Especie:");

        ComboEspecie.setBackground(new java.awt.Color(166, 81, 73));
        ComboEspecie.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComboEspecie.setForeground(new java.awt.Color(217, 185, 126));
        ComboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato", "Pez", "Pájaro" }));
        ComboEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEspecieActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 89, 42));
        jLabel1.setText("Nombre:");

        SpinnerDias2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SpinnerDias2.setModel(new javax.swing.SpinnerNumberModel(100, 100, null, 100));

        jLabel94.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(74, 89, 42));
        jLabel94.setText("Tamaño porción (gramos)");

        javax.swing.GroupLayout DatosMascotaLayout = new javax.swing.GroupLayout(DatosMascota);
        DatosMascota.setLayout(DatosMascotaLayout);
        DatosMascotaLayout.setHorizontalGroup(
            DatosMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpinnerDias2)
                    .addGroup(DatosMascotaLayout.createSequentialGroup()
                        .addGroup(DatosMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatosMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(NombreMascota)
                                .addComponent(jLabel2)
                                .addComponent(ComboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel94))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DatosMascotaLayout.setVerticalGroup(
            DatosMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel94)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerDias2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DatosOwner.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del dueño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosOwner.setOpaque(false);

        NombreOwner.setBackground(new java.awt.Color(166, 81, 73));
        NombreOwner.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        NombreOwner.setForeground(new java.awt.Color(217, 185, 126));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(74, 89, 42));
        jLabel3.setText("Número de teléfono:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(74, 89, 42));
        jLabel4.setText("Nombre:");

        NumeroTelefono.setBackground(new java.awt.Color(166, 81, 73));
        NumeroTelefono.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        NumeroTelefono.setForeground(new java.awt.Color(217, 185, 126));

        javax.swing.GroupLayout DatosOwnerLayout = new javax.swing.GroupLayout(DatosOwner);
        DatosOwner.setLayout(DatosOwnerLayout);
        DatosOwnerLayout.setHorizontalGroup(
            DatosOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosOwnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(NombreOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(NumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        DatosOwnerLayout.setVerticalGroup(
            DatosOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosOwnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DatosContrato.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosContrato.setOpaque(false);

        FechaIngreso.setBackground(new java.awt.Color(166, 81, 73));
        FechaIngreso.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        FechaIngreso.setForeground(new java.awt.Color(217, 185, 126));
        FechaIngreso.setText("DD/MM/AA");
        FechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaIngresoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(74, 89, 42));
        jLabel5.setText("Días en el hotel:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(74, 89, 42));
        jLabel6.setText("Fecha de ingreso:");

        SpinnerDias.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SpinnerDias.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        PrecioFinal.setBackground(new java.awt.Color(166, 81, 73));
        PrecioFinal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PrecioFinal.setForeground(new java.awt.Color(217, 185, 126));
        PrecioFinal.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(74, 89, 42));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Costo final:");

        PrecioPDia.setBackground(new java.awt.Color(166, 81, 73));
        PrecioPDia.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PrecioPDia.setForeground(new java.awt.Color(217, 185, 126));
        PrecioPDia.setFocusable(false);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(74, 89, 42));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Costo por día:");

        javax.swing.GroupLayout DatosContratoLayout = new javax.swing.GroupLayout(DatosContrato);
        DatosContrato.setLayout(DatosContratoLayout);
        DatosContratoLayout.setHorizontalGroup(
            DatosContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DatosContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(FechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(SpinnerDias))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PrecioFinal)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PrecioPDia)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DatosContratoLayout.setVerticalGroup(
            DatosContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrecioPDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ResetBttn.setBackground(new java.awt.Color(217, 185, 126));
        ResetBttn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ResetBttn.setForeground(new java.awt.Color(74, 89, 42));
        ResetBttn.setText("Reset");
        ResetBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NuevaMascotaLayout = new javax.swing.GroupLayout(NuevaMascota);
        NuevaMascota.setLayout(NuevaMascotaLayout);
        NuevaMascotaLayout.setHorizontalGroup(
            NuevaMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevaMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NuevaMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DatosMascota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ResetBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(DatosOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(NuevaMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InscribirBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DatosContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        NuevaMascotaLayout.setVerticalGroup(
            NuevaMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevaMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NuevaMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DatosMascota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DatosOwner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DatosContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NuevaMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InscribirBttn)
                    .addComponent(ResetBttn))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar nueva mascota", NuevaMascota);

        Alimentar.setBackground(new java.awt.Color(220, 232, 242));

        DatosMascota1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tiempos de comida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosMascota1.setOpaque(false);

        TiempoComidaPerro.setBackground(new java.awt.Color(166, 81, 73));
        TiempoComidaPerro.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        TiempoComidaPerro.setForeground(new java.awt.Color(217, 185, 126));
        TiempoComidaPerro.setFocusable(false);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(74, 89, 42));
        jLabel10.setText("Perro:");

        TiempoComidaGato.setBackground(new java.awt.Color(166, 81, 73));
        TiempoComidaGato.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        TiempoComidaGato.setForeground(new java.awt.Color(217, 185, 126));
        TiempoComidaGato.setFocusable(false);
        TiempoComidaGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoComidaGatoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(74, 89, 42));
        jLabel11.setText("Gato:");

        TiempoComidaPez.setBackground(new java.awt.Color(166, 81, 73));
        TiempoComidaPez.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        TiempoComidaPez.setForeground(new java.awt.Color(217, 185, 126));
        TiempoComidaPez.setFocusable(false);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(74, 89, 42));
        jLabel12.setText("Pez:");

        TiempoComidaAve.setBackground(new java.awt.Color(166, 81, 73));
        TiempoComidaAve.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        TiempoComidaAve.setForeground(new java.awt.Color(217, 185, 126));
        TiempoComidaAve.setFocusable(false);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(74, 89, 42));
        jLabel13.setText("Ave:");

        javax.swing.GroupLayout DatosMascota1Layout = new javax.swing.GroupLayout(DatosMascota1);
        DatosMascota1.setLayout(DatosMascota1Layout);
        DatosMascota1Layout.setHorizontalGroup(
            DatosMascota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosMascota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosMascota1Layout.createSequentialGroup()
                        .addGroup(DatosMascota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(TiempoComidaPerro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(DatosMascota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(TiempoComidaGato, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(TiempoComidaPez, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(TiempoComidaAve, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        DatosMascota1Layout.setVerticalGroup(
            DatosMascota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TiempoComidaPerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TiempoComidaGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TiempoComidaPez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TiempoComidaAve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DatosMascota2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Comida disponible", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosMascota2.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(74, 89, 42));
        jLabel14.setText("Gato:");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(74, 89, 42));
        jLabel16.setText("Ave:");

        ComidaDisponiblePerro.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponiblePerro.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponiblePerro.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponiblePerro.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponiblePerro.setFocusable(false);

        ComidaDisponibleGato.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponibleGato.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponibleGato.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponibleGato.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponibleGato.setFocusable(false);
        ComidaDisponibleGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComidaDisponibleGatoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(74, 89, 42));
        jLabel15.setText("Pez:");

        ComidaDisponiblePez.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponiblePez.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponiblePez.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponiblePez.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponiblePez.setFocusable(false);
        ComidaDisponiblePez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComidaDisponiblePezActionPerformed(evt);
            }
        });

        ComidaDisponibleAve.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponibleAve.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponibleAve.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponibleAve.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponibleAve.setFocusable(false);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(74, 89, 42));
        jLabel17.setText("Perro:");

        javax.swing.GroupLayout DatosMascota2Layout = new javax.swing.GroupLayout(DatosMascota2);
        DatosMascota2.setLayout(DatosMascota2Layout);
        DatosMascota2Layout.setHorizontalGroup(
            DatosMascota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosMascota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComidaDisponibleAve)
                    .addComponent(ComidaDisponiblePerro)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(DatosMascota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(506, 506, 506))
                            .addComponent(ComidaDisponiblePez, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComidaDisponibleGato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DatosMascota2Layout.createSequentialGroup()
                        .addGroup(DatosMascota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DatosMascota2Layout.setVerticalGroup(
            DatosMascota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponiblePerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponibleGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponiblePez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponibleAve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        AlimentarCompletoBttn.setBackground(new java.awt.Color(217, 185, 126));
        AlimentarCompletoBttn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        AlimentarCompletoBttn.setForeground(new java.awt.Color(74, 89, 42));
        AlimentarCompletoBttn.setText("Periodo de alimentación uwu");
        AlimentarCompletoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlimentarCompletoBttnActionPerformed(evt);
            }
        });

        ConflictoBttn.setBackground(new java.awt.Color(217, 185, 126));
        ConflictoBttn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ConflictoBttn.setForeground(new java.awt.Color(74, 89, 42));
        ConflictoBttn.setText("Registrar conflicto");
        ConflictoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConflictoBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlimentarLayout = new javax.swing.GroupLayout(Alimentar);
        Alimentar.setLayout(AlimentarLayout);
        AlimentarLayout.setHorizontalGroup(
            AlimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlimentarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlimentarLayout.createSequentialGroup()
                        .addComponent(DatosMascota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(DatosMascota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlimentarLayout.createSequentialGroup()
                        .addComponent(AlimentarCompletoBttn)
                        .addGap(118, 118, 118)
                        .addComponent(ConflictoBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        AlimentarLayout.setVerticalGroup(
            AlimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlimentarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DatosMascota2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DatosMascota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlimentarCompletoBttn)
                    .addComponent(ConflictoBttn))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar periodo de alimentación", Alimentar);

        Comida.setBackground(new java.awt.Color(220, 232, 242));

        DatosMascota3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ingreso de alimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosMascota3.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(74, 89, 42));
        jLabel7.setText("Especie:");

        ComboEspecieComida.setBackground(new java.awt.Color(166, 81, 73));
        ComboEspecieComida.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComboEspecieComida.setForeground(new java.awt.Color(217, 185, 126));
        ComboEspecieComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato", "Pez", "Pájaro" }));
        ComboEspecieComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEspecieComidaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(74, 89, 42));
        jLabel18.setText("Gramos:");

        SpinnerDias1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SpinnerDias1.setModel(new javax.swing.SpinnerNumberModel(100, 100, null, 100));

        javax.swing.GroupLayout DatosMascota3Layout = new javax.swing.GroupLayout(DatosMascota3);
        DatosMascota3.setLayout(DatosMascota3Layout);
        DatosMascota3Layout.setHorizontalGroup(
            DatosMascota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosMascota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosMascota3Layout.createSequentialGroup()
                        .addGroup(DatosMascota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel7)
                            .addComponent(ComboEspecieComida, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SpinnerDias1))
                .addContainerGap())
        );
        DatosMascota3Layout.setVerticalGroup(
            DatosMascota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerDias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboEspecieComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        DatosMascota21.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Comida disponible", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosMascota21.setOpaque(false);

        jLabel87.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(74, 89, 42));
        jLabel87.setText("Gato:");

        jLabel88.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(74, 89, 42));
        jLabel88.setText("Ave:");

        ComidaDisponiblePerro18.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponiblePerro18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponiblePerro18.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponiblePerro18.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponiblePerro18.setFocusable(false);

        ComidaDisponibleGato18.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponibleGato18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponibleGato18.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponibleGato18.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponibleGato18.setFocusable(false);
        ComidaDisponibleGato18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComidaDisponibleGato18ActionPerformed(evt);
            }
        });

        jLabel89.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(74, 89, 42));
        jLabel89.setText("Pez:");

        ComidaDisponiblePez18.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponiblePez18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponiblePez18.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponiblePez18.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponiblePez18.setFocusable(false);
        ComidaDisponiblePez18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComidaDisponiblePez18ActionPerformed(evt);
            }
        });

        ComidaDisponibleAve18.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponibleAve18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponibleAve18.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponibleAve18.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponibleAve18.setFocusable(false);

        jLabel90.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(74, 89, 42));
        jLabel90.setText("Perro:");

        javax.swing.GroupLayout DatosMascota21Layout = new javax.swing.GroupLayout(DatosMascota21);
        DatosMascota21.setLayout(DatosMascota21Layout);
        DatosMascota21Layout.setHorizontalGroup(
            DatosMascota21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosMascota21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComidaDisponibleAve18)
                    .addComponent(ComidaDisponiblePerro18)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota21Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(DatosMascota21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota21Layout.createSequentialGroup()
                                .addComponent(jLabel89)
                                .addGap(506, 506, 506))
                            .addComponent(ComidaDisponiblePez18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComidaDisponibleGato18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DatosMascota21Layout.createSequentialGroup()
                        .addGroup(DatosMascota21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel90)
                            .addComponent(jLabel87)
                            .addComponent(jLabel88))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DatosMascota21Layout.setVerticalGroup(
            DatosMascota21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel90)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponiblePerro18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel87)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponibleGato18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel89)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponiblePez18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel88)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponibleAve18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InscribirBttn1.setBackground(new java.awt.Color(217, 185, 126));
        InscribirBttn1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        InscribirBttn1.setForeground(new java.awt.Color(74, 89, 42));
        InscribirBttn1.setText("Registrar compra de alimento");
        InscribirBttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribirBttn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ComidaLayout = new javax.swing.GroupLayout(Comida);
        Comida.setLayout(ComidaLayout);
        ComidaLayout.setHorizontalGroup(
            ComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InscribirBttn1)
                    .addGroup(ComidaLayout.createSequentialGroup()
                        .addComponent(DatosMascota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DatosMascota21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ComidaLayout.setVerticalGroup(
            ComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DatosMascota21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DatosMascota3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InscribirBttn1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar comida", Comida);

        GestionEspecie.setBackground(new java.awt.Color(220, 232, 242));

        DatosMascota5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosMascota5.setOpaque(false);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(74, 89, 42));
        jLabel21.setText("Especie:");

        ComboEspecieComida2.setBackground(new java.awt.Color(166, 81, 73));
        ComboEspecieComida2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComboEspecieComida2.setForeground(new java.awt.Color(217, 185, 126));
        ComboEspecieComida2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato", "Pez", "Pájaro" }));
        ComboEspecieComida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEspecieComida2ActionPerformed(evt);
            }
        });

        InscribirBttn3.setBackground(new java.awt.Color(217, 185, 126));
        InscribirBttn3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        InscribirBttn3.setForeground(new java.awt.Color(74, 89, 42));
        InscribirBttn3.setText("Guardar cambios");
        InscribirBttn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribirBttn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatosMascota5Layout = new javax.swing.GroupLayout(DatosMascota5);
        DatosMascota5.setLayout(DatosMascota5Layout);
        DatosMascota5Layout.setHorizontalGroup(
            DatosMascota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosMascota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21)
                    .addComponent(ComboEspecieComida2, 0, 250, Short.MAX_VALUE)
                    .addComponent(InscribirBttn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosMascota5Layout.setVerticalGroup(
            DatosMascota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota5Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboEspecieComida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InscribirBttn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DatosMascota25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosMascota25.setOpaque(false);

        jLabel100.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(74, 89, 42));
        jLabel100.setText("Tipo de alimento:");

        jLabel101.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(74, 89, 42));
        jLabel101.setText("Costo por día:");

        ComidaDisponiblePerro20.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponiblePerro20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponiblePerro20.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponiblePerro20.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        ComidaDisponibleGato20.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponibleGato20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponibleGato20.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponibleGato20.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponibleGato20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComidaDisponibleGato20ActionPerformed(evt);
            }
        });

        jLabel102.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(74, 89, 42));
        jLabel102.setText("Tiempo de comida:");

        ComidaDisponiblePez20.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponiblePez20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponiblePez20.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponiblePez20.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ComidaDisponiblePez20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComidaDisponiblePez20ActionPerformed(evt);
            }
        });

        ComidaDisponibleAve20.setBackground(new java.awt.Color(166, 81, 73));
        ComidaDisponibleAve20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ComidaDisponibleAve20.setForeground(new java.awt.Color(217, 185, 126));
        ComidaDisponibleAve20.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel103.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(74, 89, 42));
        jLabel103.setText("Tamaño de porción:");

        javax.swing.GroupLayout DatosMascota25Layout = new javax.swing.GroupLayout(DatosMascota25);
        DatosMascota25.setLayout(DatosMascota25Layout);
        DatosMascota25Layout.setHorizontalGroup(
            DatosMascota25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosMascota25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComidaDisponibleAve20)
                    .addComponent(ComidaDisponiblePerro20)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota25Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(DatosMascota25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComidaDisponiblePez20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComidaDisponibleGato20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DatosMascota25Layout.createSequentialGroup()
                        .addGroup(DatosMascota25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel103)
                            .addComponent(jLabel100)
                            .addComponent(jLabel101))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosMascota25Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel102)
                .addGap(373, 373, 373))
        );
        DatosMascota25Layout.setVerticalGroup(
            DatosMascota25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponiblePerro20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel100)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponibleGato20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponiblePez20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComidaDisponibleAve20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GestionEspecieLayout = new javax.swing.GroupLayout(GestionEspecie);
        GestionEspecie.setLayout(GestionEspecieLayout);
        GestionEspecieLayout.setHorizontalGroup(
            GestionEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionEspecieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DatosMascota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DatosMascota25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        GestionEspecieLayout.setVerticalGroup(
            GestionEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestionEspecieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GestionEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DatosMascota25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DatosMascota5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Gestionar especie", GestionEspecie);

        Conflicto.setBackground(new java.awt.Color(220, 232, 242));

        DatosMascota22.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Características del informe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(74, 89, 42))); // NOI18N
        DatosMascota22.setOpaque(false);

        jLabel91.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(74, 89, 42));
        jLabel91.setText("Causa:");

        jLabel92.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(74, 89, 42));
        jLabel92.setText("Nombre de la mascota:");

        jLabel93.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(74, 89, 42));
        jLabel93.setText("Detalle:");

        ComboCausa.setBackground(new java.awt.Color(166, 81, 73));
        ComboCausa.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ComboCausa.setForeground(new java.awt.Color(217, 185, 126));
        ComboCausa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No se encuentra el expediente de inquilinos", "No hay alimentación para mascota en particular", "Mascota no comió" }));
        ComboCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCausaActionPerformed(evt);
            }
        });

        ComboMascotaInforme.setBackground(new java.awt.Color(166, 81, 73));
        ComboMascotaInforme.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ComboMascotaInforme.setForeground(new java.awt.Color(217, 185, 126));
        ComboMascotaInforme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No se encuentra el expediente de inquilinos", "No hay alimentación para mascota en particular", "Mascota no comió" }));
        ComboMascotaInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMascotaInformeActionPerformed(evt);
            }
        });

        SpinnerFecha.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SpinnerFecha.setModel(new javax.swing.SpinnerDateModel());

        jLabel99.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(74, 89, 42));
        jLabel99.setText("Fecha:");

        DetalleTxt.setBackground(new java.awt.Color(166, 81, 73));
        DetalleTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DetalleTxt.setForeground(new java.awt.Color(217, 185, 126));
        jScrollPane1.setViewportView(DetalleTxt);

        javax.swing.GroupLayout DatosMascota22Layout = new javax.swing.GroupLayout(DatosMascota22);
        DatosMascota22.setLayout(DatosMascota22Layout);
        DatosMascota22Layout.setHorizontalGroup(
            DatosMascota22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosMascota22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SpinnerFecha)
                    .addComponent(jLabel91, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel92, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboMascotaInforme, 0, 433, Short.MAX_VALUE)
                    .addComponent(jLabel99, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboCausa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(DatosMascota22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosMascota22Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel93)
                        .addGap(321, 321, 321))
                    .addGroup(DatosMascota22Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        DatosMascota22Layout.setVerticalGroup(
            DatosMascota22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosMascota22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosMascota22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91)
                    .addComponent(jLabel93))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosMascota22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DatosMascota22Layout.createSequentialGroup()
                        .addComponent(ComboCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel92)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboMascotaInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel99)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        GuardarBttn.setBackground(new java.awt.Color(217, 185, 126));
        GuardarBttn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        GuardarBttn.setForeground(new java.awt.Color(74, 89, 42));
        GuardarBttn.setText("Guardar");
        GuardarBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBttnActionPerformed(evt);
            }
        });

        LimpiarBttn.setBackground(new java.awt.Color(217, 185, 126));
        LimpiarBttn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        LimpiarBttn.setForeground(new java.awt.Color(74, 89, 42));
        LimpiarBttn.setText("Limpiar");
        LimpiarBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConflictoLayout = new javax.swing.GroupLayout(Conflicto);
        Conflicto.setLayout(ConflictoLayout);
        ConflictoLayout.setHorizontalGroup(
            ConflictoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConflictoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConflictoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConflictoLayout.createSequentialGroup()
                        .addComponent(LimpiarBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 358, Short.MAX_VALUE)
                        .addComponent(GuardarBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DatosMascota22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        ConflictoLayout.setVerticalGroup(
            ConflictoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConflictoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DatosMascota22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConflictoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarBttn)
                    .addComponent(LimpiarBttn))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar conflicto", Conflicto);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEspecieActionPerformed

    private void InscribirBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribirBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InscribirBttnActionPerformed

    private void ResetBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetBttnActionPerformed

    private void AlimentarCompletoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlimentarCompletoBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlimentarCompletoBttnActionPerformed

    private void ConflictoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConflictoBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConflictoBttnActionPerformed

    private void ComidaDisponiblePezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComidaDisponiblePezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComidaDisponiblePezActionPerformed

    private void ComidaDisponibleGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComidaDisponibleGatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComidaDisponibleGatoActionPerformed

    private void TiempoComidaGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoComidaGatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoComidaGatoActionPerformed

    private void ComboEspecieComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEspecieComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEspecieComidaActionPerformed

    private void ComidaDisponibleGato18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComidaDisponibleGato18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComidaDisponibleGato18ActionPerformed

    private void ComidaDisponiblePez18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComidaDisponiblePez18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComidaDisponiblePez18ActionPerformed

    private void InscribirBttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribirBttn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InscribirBttn1ActionPerformed

    private void ComboCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCausaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCausaActionPerformed

    private void ComboMascotaInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMascotaInformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMascotaInformeActionPerformed

    private void GuardarBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarBttnActionPerformed

    private void LimpiarBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiarBttnActionPerformed

    private void FechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaIngresoActionPerformed

    private void ComboEspecieComida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEspecieComida2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEspecieComida2ActionPerformed

    private void ComidaDisponibleGato20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComidaDisponibleGato20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComidaDisponibleGato20ActionPerformed

    private void ComidaDisponiblePez20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComidaDisponiblePez20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComidaDisponiblePez20ActionPerformed

    private void InscribirBttn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribirBttn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InscribirBttn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alimentar;
    private javax.swing.JButton AlimentarCompletoBttn;
    private javax.swing.JComboBox<String> ComboCausa;
    private javax.swing.JComboBox<String> ComboEspecie;
    private javax.swing.JComboBox<String> ComboEspecieComida;
    private javax.swing.JComboBox<String> ComboEspecieComida2;
    private javax.swing.JComboBox<String> ComboMascotaInforme;
    private javax.swing.JPanel Comida;
    private javax.swing.JTextField ComidaDisponibleAve;
    private javax.swing.JTextField ComidaDisponibleAve18;
    private javax.swing.JTextField ComidaDisponibleAve20;
    private javax.swing.JTextField ComidaDisponibleGato;
    private javax.swing.JTextField ComidaDisponibleGato18;
    private javax.swing.JTextField ComidaDisponibleGato20;
    private javax.swing.JTextField ComidaDisponiblePerro;
    private javax.swing.JTextField ComidaDisponiblePerro18;
    private javax.swing.JTextField ComidaDisponiblePerro20;
    private javax.swing.JTextField ComidaDisponiblePez;
    private javax.swing.JTextField ComidaDisponiblePez18;
    private javax.swing.JTextField ComidaDisponiblePez20;
    private javax.swing.JPanel Conflicto;
    private javax.swing.JButton ConflictoBttn;
    private javax.swing.JPanel DatosContrato;
    private javax.swing.JPanel DatosMascota;
    private javax.swing.JPanel DatosMascota1;
    private javax.swing.JPanel DatosMascota2;
    private javax.swing.JPanel DatosMascota21;
    private javax.swing.JPanel DatosMascota22;
    private javax.swing.JPanel DatosMascota25;
    private javax.swing.JPanel DatosMascota3;
    private javax.swing.JPanel DatosMascota5;
    private javax.swing.JPanel DatosOwner;
    private javax.swing.JTextPane DetalleTxt;
    private javax.swing.JTextField FechaIngreso;
    private javax.swing.JPanel GestionEspecie;
    private javax.swing.JButton GuardarBttn;
    private javax.swing.JButton InscribirBttn;
    private javax.swing.JButton InscribirBttn1;
    private javax.swing.JButton InscribirBttn3;
    private javax.swing.JButton LimpiarBttn;
    private javax.swing.JTextField NombreMascota;
    private javax.swing.JTextField NombreOwner;
    private javax.swing.JPanel NuevaMascota;
    private javax.swing.JTextField NumeroTelefono;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JTextField PrecioFinal;
    private javax.swing.JTextField PrecioPDia;
    private javax.swing.JButton ResetBttn;
    private javax.swing.JSpinner SpinnerDias;
    private javax.swing.JSpinner SpinnerDias1;
    private javax.swing.JSpinner SpinnerDias2;
    private javax.swing.JSpinner SpinnerFecha;
    private javax.swing.JTextField TiempoComidaAve;
    private javax.swing.JTextField TiempoComidaGato;
    private javax.swing.JTextField TiempoComidaPerro;
    private javax.swing.JTextField TiempoComidaPez;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
